<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가! -->
<!DOCTYPE bookList
[
<!ELEMENT bookList (book+)>
<!ELEMENT book (title,author+,pub,price,subtitles)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pub (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT subtitles (subtitle+)>
<!ELEMENT subtitle (#PCDATA)>
<!ATTLIST book bid CDATA #REQUIRED>
]>


<bookList>
   <book bid="1">
      <title>JAVA의 정석</title>
      <author>남궁민</author>
      <pub>도우출판사</pub>
      <price>27000원</price>
      <subtitles>
         <subtitle>자바를 시작하기 전에</subtitle>
         <subtitle><![CDATA[변수(Variable)]]></subtitle>
         <subtitle><![CDATA[연산자(Operator)]]></subtitle>
         <subtitle>조건문과 반복문</subtitle>
         <subtitle><![CDATA[배열(Array)]]></subtitle>
         <subtitle>객체지향 프로그래밍 I</subtitle>
         <subtitle>객체지향 프로그래밍 II</subtitle>
         <subtitle><![CDATA[예외처리(Exception Handling)]]></subtitle>
         <subtitle>java.lang패키지와 유용한 클래스</subtitle>
         <subtitle><![CDATA[날짜와 시간 & 형식화]]></subtitle>
         <subtitle>컬렉션 프레임웍</subtitle>
         <subtitle>지네릭스, 열거형, 애너테이션</subtitle>
         <subtitle><![CDATA[쓰레드(Thread)]]></subtitle>
         <subtitle>C람다와 스트림</subtitle>
         <subtitle><![CDATA[입출력(I/O)]]></subtitle>
         <subtitle><![CDATA[네트워킹(Networking)]]></subtitle>
      </subtitles>
   </book>
   
   <book bid="2">
      <title>다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL</title>
      <author>서진수</author>
      <author>김균도</author>
      <pub>생능출판</pub>
      <price>31040원</price>
      <subtitles>
         <subtitle>공부를 시작하기 전에 미리 알아두세요</subtitle>
         <subtitle>SELECT 명령을 이용하여 데이터를 조회합니다</subtitle>
         <subtitle>SQL 단일행 함수를 배웁니다</subtitle>
         <subtitle><![CDATA[SQL 복수행 함수(그룹 함수)를 배웁니다]]></subtitle>
         <subtitle>JOIN을 배웁니다</subtitle>
         <subtitle>DDL 명령과 딕셔너리를 배웁니다</subtitle>
         <subtitle>DML로 데이터를 관리하는 방법을 배웁니다</subtitle>
         <subtitle><![CDATA[Constraint(제약조건)를 배웁니다]]></subtitle>
         <subtitle><![CDATA[INDEX(인덱스)를 배웁니다]]></subtitle>
         <subtitle><![CDATA[VIEW(뷰)를 배웁니다]]></subtitle>
         <subtitle><![CDATA[Sub Query(서브 쿼리)를 배웁니다]]></subtitle>
         <subtitle><![CDATA[SEQUENCE(시퀀스)와 SYNONYM(동의어)를 배웁니다]]></subtitle>
         <subtitle><![CDATA[계층형 쿼리(Hierarchical Query)를 배웁니다]]></subtitle>
         <subtitle>오라클 계정 관리 방법을 배웁니다</subtitle>
         <subtitle>12c SQL에 추가된 새로운 기능</subtitle>
         <subtitle><![CDATA[Oracle PL/SQL에 입문합니다]]></subtitle>
      </subtitles>
   </book>
   
   <book bid="3">
      <title>최범균의 JSP 2.3 웹 프로그래밍: 기초부터 중급까지</title>
      <author>최범균</author>
      <pub>가메</pub>
      <price>24300원</price>
      <subtitles>
         <subtitle>PART 01 웹 프로그래밍 기초</subtitle>
         <subtitle>PART 02 필수 습득</subtitle>
         <subtitle>PART 03 개발 효율 향상</subtitle>
         <subtitle>PART 04 중급 내용 익히기</subtitle>
         <subtitle>PART 05 예제 프로젝트</subtitle>
      </subtitles>
   </book>
   
</bookList>